#!/bin/bash

root=$(readlink -f -- "$(dirname -- "$0")/..")

# Set variables
TRAEFIK_VERSION="v2.11.0"
EXTRACTED_FOLDER="$root/traefik"
TAR_FILE="$TRAEFIK_VERSION.tar.gz"
PATCH_FILE="$root/patches/traefik-2.11.0-pow_mw.patch"
DOWNLOAD_URL="https://github.com/traefik/traefik/archive/refs/tags/$TAR_FILE"

echo "Downloading $TAR_FILE..."
./scripts/get-tarball "$DOWNLOAD_URL" -O "$TAR_FILE" || exit 1

if [ -d "$EXTRACTED_FOLDER" ]; then
  echo "Cleaning up..."
  rm -rf "$EXTRACTED_FOLDER"
fi

echo "Extracting $TAR_FILE..."
mkdir  -p "$EXTRACTED_FOLDER"
tar -xzf "$TAR_FILE" -C "$EXTRACTED_FOLDER" --strip-components=1 || exit 1
rm -f "$TAR_FILE"

cd "$EXTRACTED_FOLDER" || exit 1

echo "Applying patch $PATCH_FILE..."
patch -p1 < "$PATCH_FILE" || exit 1

make binary-linux-amd64
